  CREATE TABLE IF NOT EXISTS yohh.M_ARTIST(
  ARTIST_CD VARCHAR(8) NOT NULL,
  ARTIST_NAME_KJ VARCHAR(100),
  ARTIST_NAME_KN VARCHAR(100),
  IS_DELETE INT,
  CREATE_DATE DATETIME,
  CREATE_ID VARCHAR(8),
  UPDATE_DATE DATETIME,
  UPDATE_ID VARCHAR(8),
  PRIMARY KEY(ARTIST_CD)
);
