CREATE TABLE IF NOT EXISTS yohh.M_CUSTOMER(
  CUSTOMER_NO INT NOT NULL AUTO_INCREMENT,
  CUSTOMER_NAME_KJ VARCHAR(100),
  CUSTOMER_NAME_KN VARCHAR(100),
  CUSTOMER_BIRTHDAY DATE,
  ZIP_CD VARCHAR(10),
  ADDRESS VARCHAR(300),
  TEL_NO VARCHAR(11),
  MAIL_ADDRESS VARCHAR(100),
  PASSWORD VARCHAR(100),
  CUSTOMER_RANK INT,
  IS_DELETE INT,
  CREATE_DATE DATETIME,
  CREATE_ID VARCHAR(8),
  UPDATE_DATE DATETIME,
  UPDATE_ID VARCHAR(8),
  PRIMARY KEY(CUSTOMER_NO)
);
