CREATE TABLE IF NOT EXISTS yohh.M_HINBAN(
  HINBAN_CD VARCHAR(8) NOT NULL,
  SALES_START_DATE DATETIME,
  SALES_END_DATE DATETIME,
  IS_DELETE INT,
  CREATE_DATE DATETIME,
  CREATE_ID VARCHAR(8),
  UPDATE_DATE DATETIME,
  UPDATE_ID VARCHAR(8),
  PRIMARY KEY(HINBAN_CD)
);
