CREATE TABLE IF NOT EXISTS yohh.T_ORDER_HEADER(
  ORDER_NO INT NOT NULL AUTO_INCREMENT,
  CUSTOMER_NO VARCHAR(8),
  NON_TAXED_PRICE DECIMAL(11,0),
  TAX_INC_PRICE DECIMAL(11,0),
  DESTINATION_NAME VARCHAR(100),
  DESTINATION_ADDRESS VARCHAR(300),
  HOPE_DAY DATE,
  HOPE_TIME INT,
  SHIPPING_DAY DATE,
  IS_SHIPPING INT,
  IS_DELETE INT,
  CREATE_DATE DATETIME,
  CREATE_ID VARCHAR(8),
  UPDATE_DATE DATETIME,
  UPDATE_ID VARCHAR(8),
  PRIMARY KEY(ORDER_NO,CUSTOMER_NO)
);
