CREATE TABLE IF NOT EXISTS yohh.T_ORDER_MEISAI(
  ORDER_NO INT NOT NULL AUTO_INCREMENT,
  SEQ INT NOT NULL,
  PROD_CD VARCHAR(8),
  QTY INT,
  NON_TAXED_PRICE DECIMAL(11,0),
  TAX_INC_PRICE DECIMAL(11,0),
  IS_CANCEL INT,
  CANCEL_DATE DATETIME,
  IS_DELETE INT,
  CREATE_DATE DATETIME,
  CREATE_ID VARCHAR(8),
  UPDATE_DATE DATETIME,
  UPDATE_ID VARCHAR(8),
  PRIMARY KEY(ORDER_NO,SEQ)
);
