CREATE TABLE IF NOT EXISTS yohh.T_STOCK(
  PROD_CD VARCHAR(8) NOT NULL,
  STOCK INT,
  PROVISION INT,
  IS_DELETE INT,
  CREATE_DATE DATETIME,
  CREATE_ID VARCHAR(8),
  UPDATE_DATE DATETIME,
  UPDATE_ID VARCHAR(8),
  PRIMARY KEY(PROD_CD)
);
